export function buildIssueBody(params: {
  categoryName: string;
  commentCount: number;
  npsImpact: string;
  topComments: { text: string; nps: number }[];
  recommendation: string;
  projectId?: string;
}): string {
  const quotes = params.topComments
    .map((c) => `> **NPS ${c.nps}:** ${c.text}`)
    .join("\n\n");

  const dashboardLink = params.projectId
    ? `https://localhost:3000/project/${params.projectId}/dashboard?category=${encodeURIComponent(params.categoryName)}`
    : null;

  const footer = dashboardLink
    ? `*Generated by [NPS Insight Engine](https://github.com/croblesm/nps-app) · [View in Dashboard](${dashboardLink})*`
    : `*Generated by [NPS Insight Engine](https://github.com/croblesm/nps-app)*`;

  return `## NPS Feedback: ${params.categoryName}

### Impact
- **${params.commentCount} comments** in this category
- ${params.npsImpact}

### Representative Quotes
${quotes}

### Recommended Action
${params.recommendation}

---
${footer}`;
}

export function buildIssueTitle(categoryName: string): string {
  return `[NPS Feedback] ${categoryName}`;
}
