export function buildIssueBody(params: {
  categoryName: string;
  commentCount: number;
  npsImpact: string;
  topComments: { text: string; nps: number }[];
  recommendation: string;
}): string {
  const quotes = params.topComments
    .map((c) => `> **NPS ${c.nps}:** ${c.text}`)
    .join("\n\n");

  return `## NPS Feedback: ${params.categoryName}

### Impact
- **${params.commentCount} comments** in this category
- ${params.npsImpact}

### Representative Quotes
${quotes}

### Recommended Action
${params.recommendation}

---
*Generated by [NPS Insight Engine](https://github.com/croblesm/nps-app)*`;
}

export function buildIssueTitle(categoryName: string): string {
  return `[NPS Feedback] ${categoryName}`;
}
